name:                nemo
version:             0.1.0.0
github:              "larioj/nemo"
license:             BSD3
author:              "Jesus E. Larios Murillo"
maintainer:          "preparedfortherain@gmail.com"
copyright:           "(c) 2016-2018 Jesus E. Larios Murillo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/larioj/nemo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  nemo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nemo

tests:
  nemo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nemo
